version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rehab
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./.docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5

  server:
    build:
      context: ./BE/KinectAppAPI
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings_MySQLConnection: Server=db;Port=3306;Database=rehab;User=root;Password=root;
      Logging_LogLevel_Default: Warning
    ports:
      - "80:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  ai:
    build: ./AI
    depends_on:
      - server
    networks:
      - app-network
    environment:
      # NVIDIA_VISIBLE_DEVICES: all
      SERVER_URL: http://server:8080/kinecthub?type=ai
    devices:
      - /dev/fkd
      - /dev/dri
    group_add:
      - video
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: [gpu]
    # runtime: nvidia

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
